version: '3.7'
services:
  dokgen:
    build: .
    container_name: dokgen_dev
    image: dokgen_dev:latest
    ports:
      - "8291:8080"
    volumes:
      - ./content:/app/content
    environment:
      SPRING_PROFILES_ACTIVE: dev
