apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fpdokgen
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    scalingStrategy:
      cpu:
        thresholdPercentage: 80
  liveness:
    path: actuator/health
    initialDelay: 10
    timeout: 3
  readiness:
    path: actuator/info
    initialDelay: 10
    timeout: 3
  prometheus:
    enabled: true
    path: actuator/prometheus
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
    logging:
      destinations:
        - id: loki
        - id: elastic
  {{#if consumers}}
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
    inbound:
      rules:
      {{#each consumers}}
        - application: {{app}}
          namespace: {{namespace}}
          cluster: {{cluster}}
      {{/each}}
  {{/if}}
