apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: fpdokgen
  namespace: {{namespace}}
  labels:
    team: teamforeldrepenger
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  liveness:
    path: actuator/health
    initialDelay: 10
    timeout: 3
  readiness:
    path: actuator/info
    initialDelay: 10
    timeout: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  secureLogs:
    enabled: true
