name: "Check for newer image versions"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  digest-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7.0.0
      - uses: navikt/digestabot@3302a753e533ceb9ec216de7f78345436cd636e3 # ratchet:navikt/digestabot@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: teamforeldrepenger
